### PR TITLE
Feature/localization

### PR DESCRIPTION
**Pull request by HristinaBebic**
Added translation for the components in all UI languages for all CRM systems on Export 2.0.

### CODE REVIEW

**Review by fstreicher — APPROVED** [review]
LGTM 👍

**Review by fstreicher — CHANGES_REQUESTED** [review]
Please add translations for SAP VR -> Contact

**Comment by HristinaBebic** [comment]
@fstreicher I added the translations under SAP VR - Contact

**Review by fstreicher — COMMENTED** [review]
LGTM 👍

**Review by fstreicher — APPROVED** [review]

**Pull request merged**
